src/apps/pages/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^episodes/', views.episodes, name="episodes"),
]

src/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'', include('pages.urls', namespace='pages')),


    url(r'^', include('pin_passcode.urls')),
    url(r'^admin/', include(admin.site.urls)),
]

src/apps/episodes/models.py
from django.conf import settings
from django.db import models


class Episode(models.Model):
    title = models.CharField(max_length=255, unique=True)
    date = models.DateField()
    #link_to_episode??  # only if public?

    def __str__(self):
        return "RBR: {}".format(self.title)


class Notes(models.Model):
    episode = models.ForeignKey(Episode, related_name="notes")
    text = models.TextField()
    episode_timestamp = models.CharField(max_length=12, null=True, blank=True)  # 15:30, 15m 30s, 1530
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name="notes")

    def __str__(self):
        return "Notes for {}".format(self.episode.title)


class Character(models.Model):
    is_fool = models.BooleanField(default=False)
    name = models.CharField(max_length=64)


class CharacterAppearance(models.Model):
    character = models.ForeignKey(Character, related_name="episodes")
    episode = models.ForeignKey(Episode, related_name="characters")

src/apps/pages/views.py
from django.shortcuts import render


def index(request):
    return render(request, "pages/index.html")


def episodes(request):
    return render(request, "pages/episodes.html")

src/apps/pages/templates/pages/episodes.html
{% extends "base.html" %}

{% block content %}
    <div class="container">

        <div class="row">
            <div class="col-md-12">
                <h1>Episode browser</h1>
                <form class="form-inline">
                    <div class="form-group">
                        <input type="text" class="form-control" id="exampleInputName2" placeholder="Filter (i.e. Michael Ray Bower, Gangs of Pulled Pork, Dean is gay)" size="64">
                    </div>
                    <!--
                    <div class="form-group">
                        <select class="form-control">
                            <option>Dean Carlson</option>
                            <option>Michael Ray Bower</option>
                            <option>Kyle "The Snake" Lane</option>
                        </select>
                    </div>
                    -->
                    <button type="submit" class="btn btn-default">Search</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

src/apps/pages/templates/pages/index.html
{% extends "base.html" %}

{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="row featured-fool">
                    <div class="col-md-12">
                        <h1>Featured fool</h1>
                    </div>
                    <div class="col-md-4">
                        <div class="fool-container">
                            <div class="fool">
                                <img src="http://placehold.it/300x300?text=A Fool">
                                <h4 class="name">Michael Ray Bower</h4>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-8">
                        <h3>Episode mentioned in</h3>
                        <ul class="episodes">
                            <li>
                                <span class="title">RED BAR RADIO (05-28-07)</span>
                                <span class="date">28 May 2007</span>
                            </li>
                            <li>
                                <span class="title">RED BAR RADIO (04-08-09)</span>
                                <span class="date">8 April 2009</span>
                            </li>
                            <li>
                                <span class="title">RED BAR RADIO (08-18-10)</span>
                                <span class="date">18 August 2010</span>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row fools-wall-tracker">
        <div class="col-md-12">
            <h3>Fools Wall Tracker</h3>
        </div>
        <div class="col-md-3">
            <div class="fool-container small">
                <div class="fool">
                    <img src="http://placehold.it/128x128?text=A Fool">
                    <h4 class="name">Michael Ray Bower</h4>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="fool-container small">
                <div class="fool">
                    <img src="http://placehold.it/128x128?text=A Fool">
                    <h4 class="name">Michael Ray Bower</h4>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="fool-container small">
                <div class="fool">
                    <img src="http://placehold.it/128x128?text=A Fool">
                    <h4 class="name">Michael Ray Bower</h4>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="fool-container small">
                <div class="fool">
                    <img src="http://placehold.it/128x128?text=A Fool">
                    <h4 class="name">Michael Ray Bower</h4>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

src/templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">

    <title>Fools Network</title>
    <meta name="description" content="The Fools Network">
    <meta name="author" content="Eric Carmichael">

{#    <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">#}
    <link rel="stylesheet" href="http://paintstrap.com/output/17/kuler/FC/7495208-FCFBFC-FCFBFC-FCFBFC-0E5C89-000000-212121-212121/bootstrap.min.css">
    <link rel="stylesheet" href="{% static "css/main.css" %}">

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
</head>
<body>
<div id="top-black-bg"></div>
<div id="bottom-black-bg"></div>

<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url "pages:index" %}">Fools Network</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li {% if request.path == '/' %}class="active"{% endif %}><a href="{% url "pages:index" %}">Featured</a></li>
                <li {% if '/episodes' in request.path %}class="active"{% endif %}><a href="{% url "pages:episodes" %}">Episodes</a></li>
            </ul>
            <form class="navbar-form navbar-left" role="search">
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="Search">
                </div>
                <button type="submit" class="btn btn-default">Submit</button>
            </form>
        </div>
    </div>
</nav>

<!--
<div class="container">
    <div class="row">
        <div class="col-md-12">

        </div>
    </div>
</div>
-->
{% block content %}
{% endblock %}
</body>
</html>